name: health_tracker
description: A health tracking application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  fl_chart: ^0.65.0
  path_provider: ^2.1.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  excel: ^2.1.0
  file_picker: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# 图标配置移到这里，与 flutter: 平级
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#007AFF"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/en.json
    - lib/l10n/zh.json 
    - lib/l10n/ko.json 
    - lib/l10n/ja.json